// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.team2667.stronghold;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainLeftFront;
    public static SpeedController driveTrainLeftRear;
    public static SpeedController driveTrainRightFront;
    public static SpeedController driveTrainRightRear;
    public static RobotDrive driveTrainRobotDrivePWM;
    public static CANTalon driveTrainLeftFrontCAN;
    public static CANTalon driveTrainLeftRearCAN;
    public static CANTalon driveTrainRightFrontCAN;
    public static CANTalon driveTrainRightRearCAN;
    public static RobotDrive driveTrainRobotDriveCAN;
    public static CANTalon ballManipulatorLeftSideShooter;
    public static CANTalon ballManipulatorRightSideShooter;
    public static Compressor pnumaticsCompressor;
    public static Solenoid pnumaticsShooterSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftFront = new Talon(0);
        LiveWindow.addActuator("DriveTrain", "LeftFront", (Talon) driveTrainLeftFront);
        
        driveTrainLeftRear = new Talon(2);
        LiveWindow.addActuator("DriveTrain", "LeftRear", (Talon) driveTrainLeftRear);
        
        driveTrainRightFront = new Talon(3);
        LiveWindow.addActuator("DriveTrain", "RightFront", (Talon) driveTrainRightFront);
        
        driveTrainRightRear = new Talon(4);
        LiveWindow.addActuator("DriveTrain", "RightRear", (Talon) driveTrainRightRear);
        
        driveTrainRobotDrivePWM = new RobotDrive(driveTrainLeftFront, driveTrainLeftRear,
              driveTrainRightFront, driveTrainRightRear);
        
        driveTrainRobotDrivePWM.setSafetyEnabled(true);
        driveTrainRobotDrivePWM.setExpiration(0.1);
        driveTrainRobotDrivePWM.setSensitivity(0.25);
        driveTrainRobotDrivePWM.setMaxOutput(0.5);

        driveTrainLeftFrontCAN = new CANTalon(1);
        LiveWindow.addActuator("DriveTrain", "LeftFrontCAN", driveTrainLeftFrontCAN);
        
        driveTrainLeftRearCAN = new CANTalon(2);
        LiveWindow.addActuator("DriveTrain", "LeftRearCAN", driveTrainLeftRearCAN);
        
        driveTrainRightFrontCAN = new CANTalon(3);
        LiveWindow.addActuator("DriveTrain", "RightFrontCAN", driveTrainRightFrontCAN);
        
        driveTrainRightRearCAN = new CANTalon(4);
        LiveWindow.addActuator("DriveTrain", "RightRearCAN", driveTrainRightRearCAN);
        
        driveTrainRobotDriveCAN = new RobotDrive(driveTrainLeftFrontCAN, driveTrainLeftRearCAN,
              driveTrainRightFrontCAN, driveTrainRightRearCAN);
        
        driveTrainRobotDriveCAN.setSafetyEnabled(false);
        driveTrainRobotDriveCAN.setExpiration(0.1);
        driveTrainRobotDriveCAN.setSensitivity(0.1);
        driveTrainRobotDriveCAN.setMaxOutput(0.2);

        ballManipulatorLeftSideShooter = new CANTalon(5);
        LiveWindow.addActuator("BallManipulator", "LeftSideShooter", ballManipulatorLeftSideShooter);
        
        ballManipulatorRightSideShooter = new CANTalon(6);
        LiveWindow.addActuator("BallManipulator", "RightSideShooter", ballManipulatorRightSideShooter);
        
        pnumaticsCompressor = new Compressor(0);
        
        
        pnumaticsShooterSolenoid = new Solenoid(0, 0);
        LiveWindow.addActuator("Pnumatics", "ShooterSolenoid", pnumaticsShooterSolenoid);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
